package entities;
// Generated Mar 10, 2020 1:27:33 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee",
         catalog = "employee_mng_app"
)
public class Employee implements java.io.Serializable {

    private Integer employeeId;
    private String name;
    private int age;
    private String address;
    private int salary;

    public Employee() {
    }

    public Employee(String name, int age, String address, int salary) {
        this.name = name;
        this.age = age;
        this.address = address;
        this.salary = salary;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "employee_id", unique = true, nullable = false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "age", nullable = false)
    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Column(name = "address", nullable = false, length = 45)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "salary", nullable = false)
    public int getSalary() {
        return this.salary;
    }

    public void setSalary(int salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        return "Employee Id: " + employeeId + ", name: " + name + ", age: " + age + ", adress: " + address + ", salary: " + salary;
    }

}
